### PR TITLE
Added NuGet Package and deployed it

### PR DESCRIPTION
**Pull request by hanssens**
I've taken the liberty into creating and publishing a NuGet package for this repo, both for my own use as well as effectively fixing issue #2. 

It's available at https://www.nuget.org/packages/MessageBird/

The NuGet package was created using the NuGet Package Explorer, for which I've introduced a root folder `~/NuGet/`, containing both the package details as well as the RELEASE build of the v1.0.5 dll.

@rvermeulen Should you choose to pull this and want ownership of the NuGet instance, please drop me a line. ;)

Cheers!

### CODE REVIEW

**Comment by samwierema** [comment]
Thanks @hanssens! Will be testing this this week, and will probably merge it after.

**Comment by rvermeulen** [comment]
@samwierema  @bviolier let me know if you want this merged, so I can accept this pull request.
@hanssens thanks for the effort!

**Comment by samwierema** [comment]
@hanssens since the project depends on the Json.NET package, can that be added as a dependency to this package?

**Comment by samwierema** [comment]
@rvermeulen this can be merged.

@hanssens can you assign ownership of the NuGet package to the `messagebird` user on NuGet? You can reach me at sam@messagebird.com if you have further questions.

**Comment by hanssens** [comment]
@samwierema For sure, the user `messagebird` has been added as owner. Feel free to remove me later on.

**Pull request merged**
