### PR TITLE
Adding missing content type for WhatsApp 

### PR DESCRIPTION
**Pull request by ahmetkocadogan**
issue #110

Adding missing content type whatsAppSticker

### CODE REVIEW

**Comment by ahmetkocadogan** [comment]
@epels  @marcelcorso can you please review and merge this PR if it is ok ? 

Thank you.

**Comment by marcelcorso** [comment]
hey @ahmetkocadogan. Thanks for the PR (and for the nudge)! 
I forwarded it to the conversations team to review

**Comment by ahmetkocadogan** [comment]
hey @marcelcorso thanks for the fast response 

Can you please forward these to the conversations team , thanks :)

https://github.com/messagebird/csharp-rest-api/issues/89
https://github.com/messagebird/csharp-rest-api/pull/91

**Comment by ahmetkocadogan** [comment]
Hello.

My last commit adds the rejected enum value to conversation status enum

Issue : https://github.com/messagebird/csharp-rest-api/issues/92

**Review by stnislav — APPROVED** [review]

**Review by stnislav — APPROVED** [review]

**Review by stnislav — APPROVED** [review]

**Comment by ahmetkocadogan** [comment]
thank you @stnislav . 

When can we expect a NuGet package release ?

**Comment by stnislav** [comment]
@ahmetkocadogan 
I don't know - maybe when somebody with appropriate rights will press the button - merge pull request to the master, and new release or new version will appear.

**Comment by ahmetkocadogan** [comment]
Thanks @epels

**Pull request merged**
