### PR TITLE
Target .NET Framework 4.0 and .NETStandard 2.0

### PR DESCRIPTION
**Pull request by DeluxZ**
- [x] Targetting multiple frameworks to support .NETFramework 4.0 and .NETStandard 2.0. 
- [x] Upgraded Newtonsoft.Json to the latest version because the used version doesn't support .NETStandard2.0.
- [x] Changed test framework to MSTest
- [x] Tests still run
- [ ] Please check if the AssemblyInformation is still correct.

### CODE REVIEW

**Comment by epels** [comment]
Hi @DeluxZ! Thanks a lot for opening this pull request! We'll be looking at it shortly.

**Comment by epels** [comment]
Thanks again for this PR @DeluxZ!

I have just created a `build-dotnet-standard` branch. Could you please set the base/target branch to that, rather than `master`? We'd like to integrate some more small changes before merging to master. Could you also fix the conflicts?
Thank you in advance!

**Comment by DeluxZ** [comment]
@epels I target your ```build-dotnet-standard``` branch now and resolved the conflicts. If you need any help let me know 👍

**Comment by epels** [comment]
@DeluxZ Thanks for your quick action!

**Pull request merged**
